# 04 - "list" with two names and values -> NOK

# Expected:
###########################################################################
###########################################################################
# ---
# name: a
# values: 
#   - 3
# ---
# name: b
# values: 
#   - 4
#
###########################################################################
###########################################################################

# Result:
###########################################################################
###########################################################################
# ---
# name: a
# values: 
#   - 3
#   - 2
# ---
# name: b
# values: 
#   - 4
#
###########################################################################
###########################################################################
---
helmfiles:
  - path: ../../helmfile.yaml
    values:
      - list:
          - name: a
            values:
              - 3
          - name: b
            values:
              - 4
