# 01 - "list" not provided -> OK

# Expected:
###########################################################################
###########################################################################
# ---
# name: dummy
# values: 
#   - 1
#   - 2
#
###########################################################################
###########################################################################

# Result:
###########################################################################
###########################################################################
# ---
# name: dummy
# values: 
#   - 1
#   - 2
#
###########################################################################
###########################################################################
---
helmfiles:
  - path: ../../helmfile.yaml
    values: []
