# 06 - Empty "values" -> NOK

# Expected:
###########################################################################
###########################################################################
# ---
# name: a
# values: 
#   null
#
###########################################################################
###########################################################################

# Result:
###########################################################################
###########################################################################
# ---
# name: a
# values: 
#   - 1
#   - 2
#
###########################################################################
###########################################################################
---
helmfiles:
  - path: ../../helmfile.yaml
    values:
      - list:
          - name: a
            values: []
