# 03 - "list" with only name ond one value provided -> NOK

# Expected:
###########################################################################
###########################################################################
# ---
# name: a
# values: 
#   - 3
#
###########################################################################
###########################################################################

# Result:
###########################################################################
###########################################################################
# ---
# name: a
# values: 
#   - 3
#   - 2
#
###########################################################################
###########################################################################
---
helmfiles:
  - path: ../../helmfile.yaml
    values:
      - list:
          - name: a
            values:
              - 3
