# 05 - Empty "list" -> NOK

# Expected:
###########################################################################
###########################################################################
#
###########################################################################
###########################################################################

# Result:
###########################################################################
###########################################################################
# ---
# name: dummy
# values: 
#   - 1
#   - 2
#
###########################################################################
###########################################################################
---
helmfiles:
  - path: ../../helmfile.yaml
    values:
      - list: []
